// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn serialize_member_com_amazonaws_qldb_sessionv2_command_stream_start_transaction(
    input: &crate::model::StartTransactionRequest,
) -> std::result::Result<std::vec::Vec<u8>, aws_smithy_types::Error> {
    let mut out = String::new();
    let mut object = aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::json_ser::serialize_structure_crate_model_start_transaction_request(&mut object, input);
    object.finish();
    Ok(out.into_bytes())
}

pub fn serialize_member_com_amazonaws_qldb_sessionv2_command_stream_end_session(
    input: &crate::model::EndSessionRequest,
) -> std::result::Result<std::vec::Vec<u8>, aws_smithy_types::Error> {
    let mut out = String::new();
    let mut object = aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::json_ser::serialize_structure_crate_model_end_session_request(&mut object, input);
    object.finish();
    Ok(out.into_bytes())
}

pub fn serialize_member_com_amazonaws_qldb_sessionv2_command_stream_commit_transaction(
    input: &crate::model::CommitTransactionRequest,
) -> std::result::Result<std::vec::Vec<u8>, aws_smithy_types::Error> {
    let mut out = String::new();
    let mut object = aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::json_ser::serialize_structure_crate_model_commit_transaction_request(&mut object, input);
    object.finish();
    Ok(out.into_bytes())
}

pub fn serialize_member_com_amazonaws_qldb_sessionv2_command_stream_abort_transaction(
    input: &crate::model::AbortTransactionRequest,
) -> std::result::Result<std::vec::Vec<u8>, aws_smithy_types::Error> {
    let mut out = String::new();
    let mut object = aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::json_ser::serialize_structure_crate_model_abort_transaction_request(&mut object, input);
    object.finish();
    Ok(out.into_bytes())
}

pub fn serialize_member_com_amazonaws_qldb_sessionv2_command_stream_execute_statement(
    input: &crate::model::ExecuteStatementRequest,
) -> std::result::Result<std::vec::Vec<u8>, aws_smithy_types::Error> {
    let mut out = String::new();
    let mut object = aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::json_ser::serialize_structure_crate_model_execute_statement_request(&mut object, input);
    object.finish();
    Ok(out.into_bytes())
}

pub fn serialize_member_com_amazonaws_qldb_sessionv2_command_stream_fetch_page(
    input: &crate::model::FetchPageRequest,
) -> std::result::Result<std::vec::Vec<u8>, aws_smithy_types::Error> {
    let mut out = String::new();
    let mut object = aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::json_ser::serialize_structure_crate_model_fetch_page_request(&mut object, input);
    object.finish();
    Ok(out.into_bytes())
}
