// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
pub struct SendCommandOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub session_id: std::option::Option<std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub result_stream: aws_smithy_http::event_stream::Receiver<
        crate::model::ResultStream,
        crate::error::SendCommandError,
    >,
}
impl std::fmt::Debug for SendCommandOutput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("SendCommandOutput");
        formatter.field("session_id", &self.session_id);
        formatter.field("result_stream", &self.result_stream);
        formatter.finish()
    }
}
/// See [`SendCommandOutput`](crate::output::SendCommandOutput)
pub mod send_command_output {
    /// A builder for [`SendCommandOutput`](crate::output::SendCommandOutput)
    #[non_exhaustive]
    #[derive(std::default::Default, std::fmt::Debug)]
    pub struct Builder {
        pub(crate) session_id: std::option::Option<std::string::String>,
        pub(crate) result_stream: std::option::Option<
            aws_smithy_http::event_stream::Receiver<
                crate::model::ResultStream,
                crate::error::SendCommandError,
            >,
        >,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn session_id(mut self, input: impl Into<std::string::String>) -> Self {
            self.session_id = Some(input.into());
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_session_id(mut self, input: std::option::Option<std::string::String>) -> Self {
            self.session_id = input;
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn result_stream(
            mut self,
            input: aws_smithy_http::event_stream::Receiver<
                crate::model::ResultStream,
                crate::error::SendCommandError,
            >,
        ) -> Self {
            self.result_stream = Some(input);
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_result_stream(
            mut self,
            input: std::option::Option<
                aws_smithy_http::event_stream::Receiver<
                    crate::model::ResultStream,
                    crate::error::SendCommandError,
                >,
            >,
        ) -> Self {
            self.result_stream = input;
            self
        }
        /// Consumes the builder and constructs a [`SendCommandOutput`](crate::output::SendCommandOutput)
        pub fn build(
            self,
        ) -> std::result::Result<
            crate::output::SendCommandOutput,
            aws_smithy_http::operation::BuildError,
        > {
            Ok(
                crate::output::SendCommandOutput {
                    session_id: self.session_id
                    ,
                    result_stream: self.result_stream
                        .ok_or(
                            aws_smithy_http::operation::BuildError::MissingField { field: "result_stream", details: "result_stream was not specified but it is required when building SendCommandOutput"}
                        )?
                    ,
                }
            )
        }
    }
}
impl SendCommandOutput {
    /// Creates a new builder-style object to manufacture [`SendCommandOutput`](crate::output::SendCommandOutput)
    pub fn builder() -> crate::output::send_command_output::Builder {
        crate::output::send_command_output::Builder::default()
    }
}
