[package]
name = "amazon-qldb-driver-rust"
version = "0.1.0"
authors = ["Amazon QLDB Team https://aws.amazon.com/qldb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytes = "0.5.6"
log = "0.4.11"
rusoto_core = "0.43"
rusoto_qldb_session = "0.43"
sha2 = "0.9.1"
thiserror = "1.0"
tokio = "0.2.22"

[dev-dependencies]
hex-literal = "0.3.1"
