[package]
name = "amazon-qldb-driver"
version = "0.1.0"
authors = ["Amazon QLDB Team https://aws.amazon.com/qldb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amazon-qldb-driver-core = { version = "*", path = "../amazon-qldb-driver-core" }
tokio = "1.13.0"

[dev-dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.22-alpha", package = "aws-config", features = [] }
thiserror = "1.0.29"
anyhow = "1.0.44"
tracing = "0.1.28"
tracing-subscriber = { version = "0.3.1", features = ["fmt"] }
ion-rs = "0.6.0"
ion-c-sys = "0.4.11"
