[package]
name = "amazon-qldb-driver"
version = "0.1.0"
authors = ["Amazon QLDB Team https://aws.amazon.com/qldb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amazon-qldb-driver-core = { version = "*", path = "../amazon-qldb-driver-core" }
tokio = "1.16.1"

[dev-dependencies]
aws-config = { version = "0.13.0", features = [] }
thiserror = "1.0.31"
anyhow = "1.0.57"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["fmt"] }
ion-rs = "0.9.0"
ion-c-sys = "0.4.14"
