[package]
name = "amazon-qldb-driver"
version = "0.1.0"
authors = ["Amazon QLDB Team https://aws.amazon.com/qldb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amazon-qldb-driver-core = { version = "*", path = "../amazon-qldb-driver-core" }
tokio = "1.15.0"

[dev-dependencies]
aws-config = { version = "0.3.0", features = [] }
thiserror = "1.0.30"
anyhow = "1.0.53"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.5", features = ["fmt"] }
ion-rs = "0.7.0"
ion-c-sys = "0.4.12"
