[package]
name = "amazon-qldb-driver"
version = "0.1.0"
authors = ["Amazon QLDB Team https://aws.amazon.com/qldb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amazon-qldb-driver-core = { version = "*", path = "../amazon-qldb-driver-core" }
tokio = "1.6.1"
rusoto_core = { version = "0.46.0", default_features = false, features = ["rustls"]}
rusoto_qldb_session = { version = "0.46.0", default_features = false, features = ["rustls"]}

[dev-dependencies]
thiserror = "1.0.25"
anyhow = "1.0.39"
tracing = "0.1.25"
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
ion-rs = "0.6"
ion-c-sys = "0.4.9"
