[package]
name = "amazon-qldb-driver-core"
version = "0.1.0"
authors = ["Amazon QLDB Team https://aws.amazon.com/qldb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
anyhow = "1.0.50"
tokio = { version = "1.14.0", features = ["full"] }
bytes = "1.1.0"
async-trait = "0.1.51"
# FIXME: The default features include "client" which generates an actual client.
# We don't want that! Instead, we just want the *shapes*. This allows the -core
# package to be agnostic of the actual client used.
aws_sdk_qldbsession = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.26-alpha", package = "aws-sdk-qldbsession", features = ["rustls", "client"] }
aws-hyper = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.26-alpha", package = "aws-hyper", features = [] }
aws-smithy-http = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.2.0", package = "aws-smithy-http", features = [] }
aws-types = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.26-alpha", package = "aws-types", features = [] }

sha2 = "0.9.8"
ion-rs = "0.7.0"
ion-c-sys = "0.4.12"
rand = "0.8.4"
futures = "0.3.18"
bb8 = "0.7.1"
tracing = "0.1.29"
http = "0.2.5"

[dev-dependencies]
hex-literal = "0.3.4"
ansi_term = "0.12.1"
tracing-subscriber = { version = "0.3.2", features = ["fmt"] }
