[package]
name = "amazon-qldb-driver-core"
version = "0.1.0"
authors = ["Amazon QLDB Team https://aws.amazon.com/qldb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
anyhow = "1.0.51"
tokio = { version = "1.15.0", features = ["full"] }
bytes = "1.1.0"
async-trait = "0.1.52"
# FIXME: The default features include "client" which generates an actual client.
# We don't want that! Instead, we just want the *shapes*. This allows the -core
# package to be agnostic of the actual client used.
aws-sdk-qldbsession = { version = "0.3.0", features = ["rustls"] }
aws-smithy-client = { version = "0.33.1", features = ["client-hyper", "rustls", "rt-tokio"] }
aws-smithy-http = { version = "0.33.1", features = ["rt-tokio"] }
aws-types = "0.3.0"

sha2 = "0.10.0"
ion-rs = "0.7.0"
ion-c-sys = "0.4.12"
rand = "0.8.4"
futures = "0.3.19"
bb8 = "0.7.1"
tracing = "0.1.29"
http = "0.2.5"

[dev-dependencies]
hex-literal = "0.3.4"
ansi_term = "0.12.1"
tracing-subscriber = { version = "0.3.3", features = ["fmt"] }
