[package]
name = "amazon-qldb-driver-core"
version = "0.1.0"
authors = ["Amazon QLDB Team https://aws.amazon.com/qldb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.26"
anyhow = "1.0.43"
tokio = { version = "1.10.1", features = ["full"] }
bytes = "1.1.0"
async-trait = "0.1.51"
# Note: The default features include "client" which generates an actual client.
# We don't want that! Instead, we just want the *shapes*. This allows the -core
# package to be agnostic of the actual client used.
aws_sdk_qldbsession = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.16-alpha", package = "aws-sdk-qldbsession", features = ["rustls"] }
smithy-http = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.16-alpha", package = "smithy-http", features = [] }
sha2 = "0.9.5"
ion-rs = "0.6.0"
ion-c-sys = "0.4.11"
rand = "0.8.4"
futures = "0.3.17"
bb8 = "0.7.1"
tracing = "0.1.26"
http = "0.2.4"

[dev-dependencies]
hex-literal = "0.3.3"
ansi_term = "0.12.1"
tracing-subscriber = { version = "0.2.20", features = ["fmt"] }
